# Generated by Django 4.2.1 on 2023-05-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='weight',
            new_name='order_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(upload_to='documents/%Y-%m-%d %h-%m-%s'),
        ),
        migrations.AlterField(
            model_name='order',
            name='material_type',
            field=models.CharField(choices=[('ABS', 'A'), ('PLA', 'P'), ('PETG', 'PE'), ('TPU', 'T')], max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'p'), ('complete', 'c'), ('rejected', 'r')], max_length=255),
        ),
    ]
